---
Name: Olivia
Portfolio: 3
Topic: Growth Rates
Date: January 30, 2024
---

# load packages
```{r}
library(growthrates)
library(tidyverse)
library(ggplot2)
library(here)
library(janitor)
```

# read in the data
```{r}
bison <- read_csv(here("data", "bison.csv"))
```

# visualize data
```{r}
bison_gg <- ggplot(bison, aes(x = year, y = bison)) +
  geom_line() +
  geom_point() +
  labs(x = "Year",
       y = "Bison Count") +
  theme_minimal()

bison_gg
```

# applying fit_easylinear
```{r}
# use function 'fit_easylinear' 
fit_bison_linear <- fit_easylinear(bison$year, bison$bison)

# mumax is r
coef(fit_bison_linear)
#mumax = .1338

# plot results
plot(fit_bison_linear) # the plot will note which points have highest growth rate using the data

# can also plot the log of results
```


# fit splines
```{r}
# use the funtion 'fit_spline'
fit_bison_spline <- fit_spline(bison$year, bison$bison)

# mumax is r
coef(fit_bison_spline)
# mumax = 0.5067

# plot the fitted spline
plot(fit_bison_spline)
```


# fit growth models
```{r}
p <- c(y0 = 0.01, mumax = 0.15, K = 0.1)

fit_bison_growth <- fit_growthmodel(FUN = grow_logistic,
p = p,
bison$year,
bison$bison)

coef(fit_bison_growth)
# K = 2267.286

# visualize
plot(fit_bison_growth) # not the best fit
```


## each model type gets quite different parameter values, becuase it is fitting the data differently. To get a better idea of which function is best suited for the data, always perform an initial visual inspection to get an idea if growth is linear, exponential, etc.



